### ISSUE TITLE
Trace and knock example do not work on macOS

### ISSUE THREAD

**Issue by Gohla** [kentik/netdiag#2]
The trace and knock examples give `Error: Invalid argument (os error 22)` on macOS:

```
cargo run --example trace -- 8.8.8.8
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/examples/trace 8.8.8.8`
tracing 8.8.8.8 (8.8.8.8)
Error: Invalid argument (os error 22)
```

```
cargo run --example knock -- 8.8.8.8 3
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/examples/knock 8.8.8.8 3`
knocking 8.8.8.8 (8.8.8.8)
Error: Invalid argument (os error 22)
```

The ping example works however. I'm running macOS Mojave (10.14.6) on an Intel MacBook.

I'm not sure if this is related, but all examples also require administrative access. They give `Error: Operation not permitted (os error 1)` when running on a normal user account. In contrast, the standard `traceroute` command works without administrative access.

**Comment by wg** [comment]
macOS inherited an old raw socket bug from the BSD that requires a couple of IPv4 header fields be in host byte order. This is being done as of https://github.com/kentik/netdiag/commit/e50ecc180cf113cf81da1a4627da7bf9fb7ed8ea. However knock, and tracing to an open TCP or UDP port, will not work due to other BSD-inherited behavior.

Netdiag uses raw sockets which require root privileges. I'm not sure what the macOS traceroute does, perhaps it sets the TTL with setsockopt instead of modifying the IP header directly.

**Comment by Gohla** [comment]
I see, that is unfortunate. Any plans to support these features on macOS (and Windows?) or is this library primarily aimed at supporting Linux? Might be good to note this in the README, as many people expect Rust libraries to be cross-platform. In any case, I tested out the trace example and it works now, thanks!
